-- AlterTable
ALTER TABLE "sub_service" ADD COLUMN     "extra_price" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "fix_distance" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "fix_price" DOUBLE PRECISION NOT NULL DEFAULT 0;
