import {
  Injectable,
  NotFoundException,
  ConflictException,
} from '@nestjs/common';
import { PrismaService } from 'src/core/prisma/prisma.service';
import { CreateDealerDto } from './dto/create-dealer.dto';
import { UpdateDealerDto } from './dto/update-dealer.dto';
import { DealerQueryDto } from './dto/dealer-query.dto';
import { Hash } from 'src/shared/helper/hash';
import { Prisma } from '@prisma/client';

export const dealerSelect = {
  id: true,
  formated_id: true,
  name: true,
  number: true,
  alternative_number: true,
  email: true,
  residential_address: true,
  bank_name: true,
  ifsc_code: true,
  account_number: true,
  account_holder_name: true,
  dealer_image: true,
  aadhar_image: true,
  pan_image: true,
  bankdetails_image: true,
  created_at: true,
  updated_at: true,
} as const;

@Injectable()
export class DealerService {
  constructor(private readonly prisma: PrismaService) {}

  /**
   * Creates a new dealer record
   */
  async createAsync(dto: CreateDealerDto) {
    const existing = await this.prisma.dealer.findFirst({
      where: {
        email: dto.email,
        is_deleted: false,
      },
    });

    if (existing) {
      throw new ConflictException('A dealer with this email already exists.');
    }

    const hashedPassword = await Hash.hashAsync(dto.password);

    // formated_id is generated by PostgreSQL BEFORE INSERT trigger (DLR000000X)
    const dealer = await this.prisma.dealer.create({
      data: {
        formated_id: '',
        name: dto.name,
        number: dto.number,
        alternative_number: dto.alternative_number ?? null,
        email: dto.email,
        password: hashedPassword,
        residential_address: dto.residential_address ?? null,
        bank_name: dto.bank_name ?? null,
        ifsc_code: dto.ifsc_code,
        account_number: dto.account_number,
        account_holder_name: dto.account_holder_name,
        dealer_image: dto.dealer_image ?? null,
        aadhar_image: dto.aadhar_image,
        pan_image: dto.pan_image,
        bankdetails_image: dto.bankdetails_image ?? null,
      },
      select: dealerSelect,
    });

    return dealer;
  }

  /**
   * Retrieves a paginated list of active dealers with optional search
   */
  async findAllAsync(query: DealerQueryDto) {
    const page = Number(query.page) || 1;
    const limit = Number(query.limit) || 10;
    const skip = (page - 1) * limit;

    const where: Prisma.dealerWhereInput = {
      is_deleted: false,
    };

    if (query.search?.trim()) {
      const searchTerm = query.search.trim();
      where.OR = [
        { email: { contains: searchTerm, mode: 'insensitive' } },
        { formated_id: { contains: searchTerm, mode: 'insensitive' } },
        { name: { contains: searchTerm, mode: 'insensitive' } },
        { number: { contains: searchTerm, mode: 'insensitive' } },
      ];
    }

    const [total, items] = await Promise.all([
      this.prisma.dealer.count({ where }),
      this.prisma.dealer.findMany({
        where,
        skip,
        take: limit,
        orderBy: { id: 'desc' },
        select: dealerSelect,
      }),
    ]);

    return {
      items,
      pagination: {
        page,
        limit,
        total,
        total_pages: Math.ceil(total / limit) || 1,
      },
    };
  }

  /**
   * Retrieves a single dealer by ID
   */
  async findOneAsync(id: number) {
    const dealer = await this.prisma.dealer.findFirst({
      where: {
        id,
        is_deleted: false,
      },
      select: dealerSelect,
    });

    if (!dealer) {
      throw new NotFoundException(`Dealer with ID ${id} not found.`);
    }

    return dealer;
  }

  /**
   * Updates an existing dealer record
   */
  async updateAsync(id: number, dto: UpdateDealerDto) {
    await this.findOneAsync(id);

    if (dto.email) {
      const existing = await this.prisma.dealer.findFirst({
        where: {
          email: dto.email,
          is_deleted: false,
          id: { not: id },
        },
      });
      if (existing) {
        throw new ConflictException('A dealer with this email already exists.');
      }
    }

    const updateData: Prisma.dealerUpdateInput = {};

    if (dto.name !== undefined) updateData.name = dto.name;
    if (dto.number !== undefined) updateData.number = dto.number;
    if (dto.alternative_number !== undefined) updateData.alternative_number = dto.alternative_number;
    if (dto.email !== undefined) updateData.email = dto.email;
    if (dto.password !== undefined) updateData.password = await Hash.hashAsync(dto.password);
    if (dto.residential_address !== undefined) updateData.residential_address = dto.residential_address;
    if (dto.bank_name !== undefined) updateData.bank_name = dto.bank_name;
    if (dto.ifsc_code !== undefined) updateData.ifsc_code = dto.ifsc_code;
    if (dto.account_number !== undefined) updateData.account_number = dto.account_number;
    if (dto.account_holder_name !== undefined) updateData.account_holder_name = dto.account_holder_name;
    if (dto.dealer_image !== undefined) updateData.dealer_image = dto.dealer_image;
    if (dto.aadhar_image !== undefined) updateData.aadhar_image = dto.aadhar_image;
    if (dto.pan_image !== undefined) updateData.pan_image = dto.pan_image;
    if (dto.bankdetails_image !== undefined) updateData.bankdetails_image = dto.bankdetails_image;

    const updated = await this.prisma.dealer.update({
      where: { id },
      data: updateData,
      select: dealerSelect,
    });

    return updated;
  }

  /**
   * Soft-deletes a dealer by ID
   */
  async deleteAsync(id: number, deletedById?: number) {
    await this.findOneAsync(id);

    await this.prisma.dealer.update({
      where: { id },
      data: {
        is_deleted: true,
        is_deleted_by: deletedById ?? null,
      },
    });

    return true;
  }
}
