import {
  Injectable,
  NotFoundException,
  ConflictException,
} from '@nestjs/common';
import { PrismaService } from 'src/core/prisma/prisma.service';
import { CreateDealerDto } from './dto/create-dealer.dto';
import { UpdateDealerDto } from './dto/update-dealer.dto';
import { DealerQueryDto } from './dto/dealer-query.dto';
import { Hash } from 'src/shared/helper/hash';
import { Prisma } from '@prisma/client';

@Injectable()
export class DealerService {
  constructor(private readonly prisma: PrismaService) {}

  /**
   * Creates a new dealer record
   */
  async createAsync(dto: CreateDealerDto) {
    const existing = await this.prisma.dealer.findFirst({
      where: {
        email: dto.email,
        is_deleted: false,
      },
    });

    if (existing) {
      throw new ConflictException('A dealer with this email already exists.');
    }

    const hashedPassword = await Hash.hashAsync(dto.password);

    // formated_id is generated by PostgreSQL BEFORE INSERT trigger (DLR000000X)
    const dealer = await this.prisma.dealer.create({
      data: {
        email: dto.email,
        password: hashedPassword,
        formated_id: '',
      },
      select: {
        id: true,
        formated_id: true,
        email: true,
        created_at: true,
        updated_at: true,
      },
    });

    return dealer;
  }

  /**
   * Retrieves a paginated list of active dealers with optional search
   */
  async findAllAsync(query: DealerQueryDto) {
    const page = Number(query.page) || 1;
    const limit = Number(query.limit) || 10;
    const skip = (page - 1) * limit;

    const where: Prisma.dealerWhereInput = {
      is_deleted: false,
    };

    if (query.search?.trim()) {
      const searchTerm = query.search.trim();
      where.OR = [
        { email: { contains: searchTerm, mode: 'insensitive' } },
        { formated_id: { contains: searchTerm, mode: 'insensitive' } },
      ];
    }

    const [total, items] = await Promise.all([
      this.prisma.dealer.count({ where }),
      this.prisma.dealer.findMany({
        where,
        skip,
        take: limit,
        orderBy: { id: 'desc' },
        select: {
          id: true,
          formated_id: true,
          email: true,
          created_at: true,
          updated_at: true,
        },
      }),
    ]);

    return {
      items,
      pagination: {
        page,
        limit,
        total,
        total_pages: Math.ceil(total / limit) || 1,
      },
    };
  }

  /**
   * Retrieves a single dealer by ID
   */
  async findOneAsync(id: number) {
    const dealer = await this.prisma.dealer.findFirst({
      where: {
        id,
        is_deleted: false,
      },
      select: {
        id: true,
        formated_id: true,
        email: true,
        created_at: true,
        updated_at: true,
      },
    });

    if (!dealer) {
      throw new NotFoundException(`Dealer with ID ${id} not found.`);
    }

    return dealer;
  }

  /**
   * Updates an existing dealer record
   */
  async updateAsync(id: number, dto: UpdateDealerDto) {
    await this.findOneAsync(id);

    if (dto.email) {
      const existing = await this.prisma.dealer.findFirst({
        where: {
          email: dto.email,
          is_deleted: false,
          id: { not: id },
        },
      });
      if (existing) {
        throw new ConflictException('A dealer with this email already exists.');
      }
    }

    const updateData: Prisma.dealerUpdateInput = {};

    if (dto.email) {
      updateData.email = dto.email;
    }

    if (dto.password) {
      updateData.password = await Hash.hashAsync(dto.password);
    }

    const updated = await this.prisma.dealer.update({
      where: { id },
      data: updateData,
      select: {
        id: true,
        formated_id: true,
        email: true,
        created_at: true,
        updated_at: true,
      },
    });

    return updated;
  }

  /**
   * Soft-deletes a dealer by ID
   */
  async deleteAsync(id: number, deletedById?: number) {
    await this.findOneAsync(id);

    await this.prisma.dealer.update({
      where: { id },
      data: {
        is_deleted: true,
        is_deleted_by: deletedById ?? null,
      },
    });

    return true;
  }
}
