import { Injectable, BadRequestException, NotFoundException } from '@nestjs/common';
import { PrismaService } from 'src/core/prisma/prisma.service';
import { CreateLeadDto } from './dto/create-lead.dto';
import { MapsService } from '../../services/maps/maps.service';

@Injectable()
export class LeadService {
  constructor(
    private readonly _prismaService: PrismaService,
    private readonly _mapsService: MapsService,
  ) {}

  async create(vendorId: number, createLeadDto: CreateLeadDto) {
    const { tag_locations, ...leadData } = createLeadDto;

    // Verify the driver belongs to the vendor
    const driver = await this._prismaService.driver.findFirst({
      where: { id: leadData.driver_id, vendor_id: vendorId }
    });

    if (!driver) {
      throw new BadRequestException('Selected driver does not belong to this vendor.');
    }

    if (!driver.vehicle_id) {
      throw new BadRequestException('Selected driver does not have an assigned vehicle.');
    }

    // Resolve location data using MapsService
    const startLocationData = await this._mapsService.resolveAddressByPlaceIdAsync(leadData.start_location);
    const endLocationData = await this._mapsService.resolveAddressByPlaceIdAsync(leadData.end_location);

    // Removed tag_locations_data since tags are now just simple text array

    // Create the lead
    const newLead = await this._prismaService.lead.create({
      data: {
        ...leadData,
        formated_id: '', // Generated by SQL trigger
        vendor_id: vendorId,
        vehicle_id: driver.vehicle_id,
        start_location_data: startLocationData as any,
        end_location_data: endLocationData as any,
        tag_locations: tag_locations || [],
      },
    });

    return newLead;
  }

  async calculateRoute(startLocation: string, endLocation: string) {
    const distanceMatrix = await this._mapsService.getDistanceMatrixAsync(
      startLocation,
      endLocation
    );

    return {
      distance: distanceMatrix.distance.formatted,
      time: distanceMatrix.travel_time.formatted,
    };
  }

  async getByIdAsync(id: number) {
    const lead = await this._prismaService.lead.findUnique({
      where: { id },
      include: {
        vendor: true,
        driver: true,
        customer: true,
        vehicle: true,
        sub_service: { include: { service: true } },
        locations: true,
        otps: true,
        pickup_evcrf: { include: { damages: true } },
        dropoff_evcrf: true,
        reviews: true,
      },
    });

    if (!lead) {
      throw new NotFoundException(`Lead with ID ${id} not found`);
    }

    return lead;
  }

  async getLeadOtpsAsync(id: number) {
    const lead = await this._prismaService.lead.findUnique({
      where: { id },
      include: { otps: true },
    });

    if (!lead) {
      throw new NotFoundException(`Lead with ID ${id} not found`);
    }

    return lead.otps;
  }
}
